### ISSUE TITLE
Extract Way from osm.pbf data ?

### ISSUE THREAD

**Issue by Fares-Tabet** [OsmSharp/core#99] opened 2020-02-18 22:50 UTC
Hello,

My ultimate goal is to extract from the data the "highway" value of each road (I am trying to build a network graph of each highway class in a specific region using OSM data) and I've read that this tag is contained inside the Way object, but using the sample examples and PBFOsmStreamSource all I am able to extract from the files are the Node objects, and not the Way objects that I need. 

I tried to go through all elements in the PBFStreamSource but all that's there are Nodes (even without filtering the data). In the complete stream sample we have the below code, but the program never enters the if statement. 

`var complete = filtered.ToComplete();

                // enumerate result.
                foreach (var osmGeo in complete)
                {
                    if (osmGeo.Type == OsmSharp.OsmGeoType.Way)
                    { // the nodes are still in the stream, we need them to construct the 'complete' objects.
                        Console.WriteLine(osmGeo.ToString());
                    }
                }` 

Any help would be highly appreciated, and thank you for your time !

**Comment by blackboxlogic** [comment] 2020-06-09 19:10
You might be using `while (reader.MoveNextNode())` instead of `while (reader.MoveNext())`?
I just run a test and was able to parse every object from a pbf file including nodes ways and relations. If you're still having trouble, please post the code where you create and read from the `PBFOsmStreamSource`, and maybe provide a small sample pbf that produces the problem.

**Comment by blackboxlogic** [comment] 2020-06-09 19:14
I accidentally deleted my comment, so sorry if you're notified twice.
You might be using `while (reader.MoveNextNode())` when you should be using `while (reader.MoveNext())`. I just tested on my computer and could get all three element types from a pbj using the `PBFOsmStreamSource`. If you're still having trouble maybe post the code where you create and use the `PBFOsmStreamSource`, and a small sample pbf file that causes the problem.

**Comment by tonibabieka** [comment] 2020-06-16 14:04
I´using it as in the examples. no use of reader.MoveNext() at all;
` using (var fileStream = File.OpenRead("luxembourg-latest.osm.pbf"))
 {
    var source = new PBFOsmStreamSource(fileStream);
    var filtered = from osmGeo in source
                               where osmGeo.Type == OsmSharp.OsmGeoType.Way
                               select osmGeo;
     var complete = filtered.ToComplete();
     complete.Count();
}
`
I get Count = 0
Thanks

**Comment by blackboxlogic** [comment] 2020-06-16 15:11
You filtered out the nodes _before_ asking the nodes to `complete` the ways. The innards of your `using` should be:
```c#
    var source = new PBFOsmStreamSource(fileStream);
    var completeSource = source.ToComplete();
    var filtered = from osmGeo in completeSource where osmGeo.Type == OsmGeoType.Way select osmGeo;
    filtered.Count();
```
Could you point me to where you got the sample code, I'll fixy.

**Comment by easyest** [comment] 2021-02-09 12:58
The sample code is FROM YOUR OWN DOCUMENTATION! Having in mind, that Your documentation (https://docs.itinero.tech/docs/osmsharp/index.html) consists of 6 pages (4 of them are "examples"), I understand that it is really complicated to find this sample. Moreover, Your documentation states, that:
```c#
  // convert to complete stream.
 // WARNING: nodes that are partof powerlines will be kept in-memory.
  //          it's important to filter only the objects you need **before** 
  //          you convert to a complete stream otherwise all objects will 
  //          be kept in-memory.
```
So, it states that it is important to filter **BEFORE**.

**Comment by blackboxlogic** [comment] 2021-02-09 15:27
> I understand that it is really complicated to find this sample

Context: this isn't my project. I'm just an internet stranger helping you. You're welcome.

**Comment by xivk** [comment] 2021-02-09 16:19
@easyest we are all volunteers here, you are getting free code with some free documentation **without any guarantees or obligations** from the maintainers. Please be friendly or otherwise just leave, thanks!

**Comment by xivk** [comment] 2021-05-10 11:46
@easyest The cause of this issue could be that the test file you are using was not downloaded completely. The PBF stream does contain all types of objects but calling ToComplete() will remove all ways that have a node missing.

Closing this issue as it is already over a year old.

**Closed by xivk** 2021-05-10 11:46 UTC

**Comment by easyest** [comment] 2021-05-10 12:14
It is not possible - data file is an extract for the country downloaded from geofabrik. And @blackboxlogic already did give an answer. The only problem is that the documentation says to do it in the wrong way :)
